### ISSUE TITLE
Infinite Card Binders can have their UUID Wiped when renaming them

### ISSUE THREAD

**Issue by Yslohr** [CAS-ual-TY/YgoDuelingMod#11] opened 2022-07-31 13:12 UTC
As stated UUIDs can be wiped while renaming said infinite card binders in an anvil
![2022-07-31_02 28 25](https://user-images.githubusercontent.com/22603163/182027890-e3dc12d5-fe75-4261-b84b-3e7d7f6f6c31.png)
![2022-07-31_15 02 00](https://user-images.githubusercontent.com/22603163/182027891-39b9287d-146d-48c7-baea-e457ece33ee9.png)
![2022-07-31_15 02 06](https://user-images.githubusercontent.com/22603163/182027892-0b7f87a5-cdfa-4c71-8791-9598fc39ceaf.png)
![2022-07-31_15 02 16](https://user-images.githubusercontent.com/22603163/182027895-65c9c7de-95f1-4a86-aed3-d3eb20bc4166.png)
![2022-07-31_15 02 27](https://user-images.githubusercontent.com/22603163/182027896-3e4794f9-8572-40a8-87fa-0eecb03b36a5.png)
:
Here are my logs:
[latest.log](https://github.com/CAS-ual-TY/YgoDuelingMod/files/9228915/latest.log)
I'm running Minecraft 1.16.5 with Minecraft Forge version 36.2.33
The List of mods currently installed:
- appleskin-forge-mc1.16.x-2.4.0
- architectury-1.30.57
- AttributeFix-1.16.5-10.1.4
- AutoRegLib-1.6-49
- BetterCaves-Forge-1.16.4-1.1.2
- cfm-7.0.0pre22-1.16.3
- Controlling-7.0.0.28
- CraftingTweaks_1.16.5-12.2.1
- CustomNPCs-1.16.5.20220226
- ferritecore-2.0.7-forge
- flatbedrock-1.16.4-1.1.6
- ftb-backups-2.1.2.2
- ftb-library-forge-1605.3.4-build.90
- Hwyla-forge-1.10.11-B78_1.16.2
- invtweaks-1.16.4-1.0.1
- jei-1.16.5-7.7.0.98
- journeymap-1.16.5-5.7.3
- JustEnoughResources-1.16.5-0.12.1.133
- mcw-roofs-2.0.1-mc1.16.5-4
- moreoverlays-1.18.18-mc1.16.5
- MouseTweaks-2.14-mc1.16.2
- OptiFine_1.16.5_HD_U_G8
- overloadedarmorbar-5.1.0
- Placebo-1.16.5-4.6.1
- Quash Economies 4.3.1
- spark-forge
- ToastControl-1.16.5-4.4.0
- ydm-1.16.5-2.10.2.43

**Comment by CAS-ual-TY** [comment] 2022-08-10 17:30
Sorry for the late reply. Im in holidays. Does this also happen without any other mods installed? Because I am not able to reproduce it using only YDM

**Comment by CAS-ual-TY** [comment] 2022-09-16 13:54
Fixed in a93d80076f14383eb669c1f3effa511f54d860a3

**Closed by CAS-ual-TY** 2022-09-16 13:54 UTC
